name: besaver
description: Gestor de despesas.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.8.0
  numberpicker: ^2.1.2
  intl: ^0.18.1
  email_validator: ^2.1.17
  fl_chart: ^0.62.0

 
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
